# Generated by Django 4.2.3 on 2023-07-24 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friends_app', '0002_actor_director_alter_movie_content_alter_movie_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'verbose_name': 'Актеры', 'verbose_name_plural': 'Актеры'},
        ),
        migrations.AlterModelOptions(
            name='director',
            options={'verbose_name': 'Режиссеры', 'verbose_name_plural': 'Режиссеры'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'Фильмы', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='friends_app.director'),
        ),
    ]
