# Generated by Django 4.2.3 on 2023-07-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends_app', '0003_alter_actor_options_alter_director_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='content',
            field=models.TextField(blank=True, verbose_name='Биография'),
        ),
        migrations.AddField(
            model_name='director',
            name='content',
            field=models.TextField(blank=True, verbose_name='Биография'),
        ),
    ]
