# Generated by Django 4.2.3 on 2023-07-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends_app', '0005_alter_actor_age_alter_director_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='photo',
            field=models.ImageField(default='', upload_to='gallery/%y/%m/%d', verbose_name='Фото'),
        ),
    ]
