# Generated by Django 4.2.3 on 2023-07-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends_app', '0006_director_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='photo',
            field=models.ImageField(default='', upload_to='gallery/%y/%m/%d', verbose_name='Фото'),
        ),
    ]
