# Generated by Django 4.2.3 on 2023-07-26 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends_app', '0009_photos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photos',
            options={'verbose_name': 'Фотокарточки', 'verbose_name_plural': 'Фотокарточки'},
        ),
    ]
