# Generated by Django 4.2.3 on 2023-07-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends_app', '0011_movie_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(default='', max_length=100),
        ),
    ]
