# Generated by Django 4.2.3 on 2023-07-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends_app', '0015_actor_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='slug',
            field=models.SlugField(default='', max_length=100, verbose_name='URL'),
        ),
    ]
