# Generated by Django 4.2.3 on 2023-07-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends_app', '0016_director_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_song', models.CharField(blank=True, default='', max_length=50, verbose_name='Название трека')),
                ('artist', models.CharField(blank=True, default='', max_length=50, verbose_name='Исполнитель')),
                ('song', models.FileField(blank=True, default='', upload_to='sound_track_in_friends/%y/%m/%d', verbose_name='Композиция')),
            ],
        ),
    ]
