# Generated by Django 4.2.3 on 2023-07-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends_app', '0017_audiotrack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='years',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год производства'),
        ),
    ]
