# Generated by Django 4.2.3 on 2023-08-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends_app', '0018_alter_movie_years'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Имя пользователя')),
                ('comment', models.TextField()),
            ],
            options={
                'verbose_name': 'Комментарии',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
